import { getProviders, signIn } from 'next-auth/react';
import Head from 'next/head'


function Login({ providers }) {
const imagenLogin = "/SpotifyIcon.png"
    return (
        <div className='flex flex-col items-center bg-black min-h-screen w-full justify-center'>
            <Head>
                <title>Spotify login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={imagenLogin} />
            </Head>

            <img className='w-52 mb-5' src={imagenLogin} alt="logo" />

            {Object.values(providers).map((provider) => (
                <div key={provider.id}>
                    <button className='bg-gonza-violet-600 text-white p-5 rounded-full'
                    onClick={() => signIn(provider.id, {callbackUrl: "/"})}
                    >Login with {provider.name}</button>
                </div>
            ))}

        </div>
    )
}

export default Login

export async function getServerSideProps() {
    const providers = await getProviders();
    return {
        props: {
            providers,
        },
    };
}
